### ISSUE TITLE
Adding a new backend requires subclassing both Language and CompileExpressionVisitor

### ISSUE THREAD

**Issue by billhowe** [uwescience/raco#401]
If I want to write a custom syntax for a new backend language, I will always need to subclass Language and override body, compile_attribute, etc. 

But if I need to change the syntax for EQ, AND, etc., I appear to need to subclass CompileExpressionVisitor, override the appropriate methods, then override compile_expression in my Language subclass to use the new visitor.

The goal of the Language class was to provide a single point of control for implementing new backend syntaxes.  

So I think CompileExpressionVisitor should call an appropriate Language method in every visit method.

**Comment by bmyerz** [comment]
This seems reasonable to me. We can address this in the branch that needs it, #404. See comments there

**Comment by billhowe** [comment]
I think I fixed this in 8ee8ffa979caceae1e77745b98178e72746b9b6d and d159e3cd24ee0cf192599d6241f448edbd617dd3 

The `CompileExpressionVisitor` now uses constants defined in the `Language` object.  So you just need to override the default constants to implement a custom syntax for your language.  e.g., to "=" instead of "==" as I needed in #404.

If you want to do fancier expression compiling, such as to use non-infix notation, you can still override `language.expression_combine`
