### ISSUE TITLE
MyriaL: String literals cannot contain double quotes?

### ISSUE THREAD

**Issue by billhowe** [uwescience/raco#403]
Looking at raco/myrial/parser.py and raco/expression/expression.py, it appears there is no escape syntax for double quotes in string literals.

Wish list: It would be nice to have the choice of single or double quotes a la python.

- [x] fix
- [ ] test(s)

**Comment by bmyerz** [comment]
I have a possible fix in https://github.com/uwescience/raco/commit/7df119ec9b47e5181600e58311e4733fc0bb988a

Since python supports this, I only had to change the MyriaL parser
