### ISSUE TITLE
BroadcastBeforeCross rule in myrialang should map CrossProduct to RightHashJoin, not SymmetricHashJoin

### ISSUE THREAD

**Issue by senderista** [uwescience/raco#422]
In the MyriaL compiler, currently the CrossProduct logical operator is unconditionally mapped to the SymmetricHashJoin MyriaX operator. If one of the inputs to CrossProduct is a Broadcast logical operator, and the other input is a partitioned relation, then unless the cardinality of the (unpartitioned) Broadcast child is known to be smaller than the partitions of the other input, we should use RightHashJoin, since we can expect the cardinality of the unpartitioned Broadcast input to (locally) be larger than the other, partitioned input. That should help avoid out-of-memory errors in cross-product queries from materializing the Broadcast input in SymmetricHashJoin, since the Broadcast input does not need to be materialized at all if it is the probe input to RightHashJoin. The only downside is that RightHashJoin cannot be fully pipelined, since it must block until the hash table for the build input is populated.

For an example of the current behavior, see the second query plan in this comment: https://github.com/uwescience/raco/issues/419#issue-75091172 (note that CrossProduct in the diagram is mapped to SymmetricHashJoin).

**Comment by bmyerz** [comment]
@jortiz16 are cross products truly common in MyriaX queries you are doing, or do they usually show up in places that Raco fails to turn a crossproduct+filter into a equijoin?

I'm trying to figure out what the right fix is here.

**Comment by jortiz16** [comment]
@bmyerz I don't want to use cross products, but they manage to show up if I don't write the query a specific way. One example is the casting which I talked about earlier. Another example is the writing the tables in the wrong order in the "from" clause. This is another issue entirely. In short, I don't want cross products at all! I can provide the example dataset and queries as well if you're interested. Thanks! 

Also, let me know if there is another way I can help. I'm not familiar with Raco, but I'd be happy to learn how to add a rule to prevent this from happening as well.

**Comment by bmyerz** [comment]
Great! Thats what I was hoping. Let's try to fix all these situations in Raco.

Can you post another issue demonstrating two queries with the from clause switching that I can replicate?

**Comment by senderista** [comment]
Also, we could map CrossProduct to an arbitrarily (but evenly) partitioned shuffle of the two relations over a 2D grid, which would have data movement of `(R+S)*sqrt(P)`. The broadcast plan would have data movement `S*P`, where `S` is the broadcast relation. Presumably a cost-based optimizer could figure out which cost was lower.
