### ISSUE TITLE
Some equijoin-connected join graphs result in plans with CrossProducts

### ISSUE THREAD

**Issue by bmyerz** [uwescience/raco#455]
example:
TPC-H Q2
https://github.com/uwescience/tpch-radish/blob/master/q2.myl

![image](https://cloud.githubusercontent.com/assets/1979690/8564186/e0d75f52-24fd-11e5-9896-df088d991a51.png)

The solution for this particular case is to write a rule that swaps join order so that we use edges in the join graph.

**Comment by stechu** [comment]
We know this for a while. Fixing this will be great! 
If you just want a quick work around to run TPC-H, a quick hack is to make the order of tables in the "From" clause as the join order you want.

**Comment by bmyerz** [comment]
@stechu thanks, this worked and the workaround is as convenient as I could hope for (at least for linear join graphs) until we have cost-based join optimization

**Comment by bmyerz** [comment]
closing because I don't think we are ready to propose what we want the solution to be here
