### ISSUE TITLE
MyriaL rules should elide shuffle when joins can be performed locally

### ISSUE THREAD

**Issue by senderista** [uwescience/raco#462]
A large join (https://rest.myria.cs.washington.edu:1776/query/query-77554) ran out of memory due to shuffle even though no shuffle was necessary since join attributes were the same as partitioning attributes. We could perform the local join either in Myria or in Postgres, although the latter would be necessary when the joined local relations (or even one of them, say the build side of a RightHashJoin) do not fit in memory. A prerequisite for this is that we have reliable partitioning information in the MyriaX catalog, which doesn't seem to be the case currently (https://github.com/uwescience/myria/issues/766).

**Comment by senderista** [comment]
A prerequisite for ensuring that partitioning information is reliably propagated to storage metadata: https://github.com/uwescience/raco/issues/466

**Comment by bmyerz** [comment]
fixed in #467
