### ISSUE TITLE
Add partitioning information to Raco's catalog interface

### ISSUE THREAD

**Issue by senderista** [uwescience/raco#465]
This is a requirement for https://github.com/uwescience/myria/issues/766

On Thu, Aug 13, 2015 at 1:01 PM, Bill Howe <billhowe@cs.washington.edu> wrote:

On Thu, Aug 13, 2015 at 12:46 PM, Brandon Myers <bdmyers@cs.washington.edu> wrote:
We just need to add partitioning to racos catalog interface.

Brandon: Can you take a stab at a design for this?  

One thought is to leave get_scheme as is, but to just add another call, say get_partitioning(rel_key), that returns a list of attributes on which the relation is partitioned.  

Not sure if we need the workers as well.  If so, I'd imagine making that a separate call get_workers(rel_key)

(We could also have a similar call get_order(rel_key) that returns a list of attributes on which the relation is sorted, but we can do that once it's motivated.)

**Comment by bmyerz** [comment]
see #467

**Comment by senderista** [comment]
Fixed in https://github.com/uwescience/raco/pull/450.
