### ISSUE TITLE
MyriaL rule should extract partitioning info from exchange operators and propagate to Store operator

### ISSUE THREAD

**Issue by senderista** [uwescience/raco#466]
From @jingjingwang:

> I think a neat way of implementing it might be: adding a rule in raco to extract the partition function from a ShuffleProducer and send it to a Store (and we need to add the PF as a field in DbInsert in MyriaX), then when the server wants to update the metadata of a stored relation, write the PF into catalog. Otherwise, the code may look ugly if we do it purely on the MyriaX side, since we need to dig into query plans.

**Comment by bmyerz** [comment]
this seems like a good idea. A full solution involving partition info in Raco should make it part of the schema that every operator has anyway.

**Comment by billhowe** [comment]
For the immediate task, a rule seems nice: Shuffle -> Store ==> Shuffle -> PartitionedStore

But Brandon makes a good point about making this information more broadly available.  

Each operator knows how it modifies the scheme, and similarly each operator knows how it modifies the partitioning.

I hesitate to pollute the Scheme object with this info, but that might be the best way.

I suppose it's either a method on the scheme object ("partitionedon") or a method on the operator interface itself (maybe "get_partitioning" to align with "get_scheme").

In either case, the method can return a list of attributes.

If partitioning information isn't available, we could default to all attributes (implying that it doesn't matter) or maybe use the empty list as a distinguished value to indicate "no partitioning."  I vote for the former to avoid special logic for the empty list.

**Comment by bmyerz** [comment]
> If partitioning information isn't available, we could default to all attributes (implying that it doesn't matter) > or maybe use the empty list as a distinguished value to indicate "no partitioning." I vote for the former to > avoid special logic for the empty list.

I don't the all-attributes base case because it seems wrong: if two rows are identical  then they would be partitioned the same but this does not follow for no partitioning.

> I hesitate to pollute the Scheme object with this info, but that might be the best way.
> I suppose it's either a method on the scheme object ("partitionedon") or a method on the operator 
> interface itself (maybe "get_partitioning" to align with "get_scheme").

After pondering this for a little while I think I agree. If we follow the existing pattern for this kind of information (`num_tuples`) then we would it to the operators and catalog, while the scheme is just that.

**Comment by billhowe** [comment]
On Mon, Aug 17, 2015 at 1:14 PM, Brandon Myers <notifications@github.com>
wrote:

> If partitioning information isn't available, we could default to all
> attributes (implying that it doesn't matter) > or maybe use the empty list
> as a distinguished value to indicate "no partitioning." I vote for the
> former to > avoid special logic for the empty list.
>
> I don't the all-attributes base case because it seems wrong: if two rows
> are identical then they would be partitioned the same but this does not
> follow for no partitioning.
>

That makes sense.  Stupid bag semantics; always causing trouble.

**Comment by bmyerz** [comment]
Above I said empty list should be disallowed, but it seems more natural to have empty list to mean "no information". Then the invariant is that an attribute in the list is known to be partitioned and an attribute not in the list is unknown to be partitioned.

**Comment by billhowe** [comment]
This seems great.
