### ISSUE TITLE
Wire up partitioning optimization with Myria

### ISSUE THREAD

**Issue by bmyerz** [uwescience/raco#472]
use the changes in #467: particularly make sure that the partitioning optimizations work with a real connection to myria catalog

depends on #467 

- [x] @senderista update myria catalog interface to get myria's catalog partition info (note that the myria catalog interface is buried in another unmerged branch https://github.com/uwescience/raco/blob/raco_only_execution/raco/backends/myria/catalog.py part of PR #450 )
- [x] @senderista myriax store `compileme` to json needs to include partitioning info

**Comment by senderista** [comment]
@bmyerz I'm confused; does #450 need to be merged in its entirety before I can update the catalog interface to include partitioning info? Should I make the update on that branch and wait for you to merge the PR before proceeding with the final MyriaX integration?

**Comment by bmyerz** [comment]
@senderista The only things required from #450 are `myria/connection.py` and `myria/catalog.py`.
But I think we will just try to merge all of #450. (I did a test merge with newer changes and they __don't__ conflict badly with all the refactorings in that branch)

You should build your changes off of https://github.com/uwescience/raco/tree/raco_only_execution

**Comment by senderista** [comment]
This is blocking on #450. The local join optimization is now tested end-to-end.

**Comment by senderista** [comment]
This was fixed in #450 by https://github.com/uwescience/raco/commit/7d5c61a8fca001ed70058a12ec23c55f6eca2f49 and related commits.
