### ISSUE TITLE
Upgrade travis

### ISSUE THREAD

**Issue by bmyerz** [uwescience/raco#474]
http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

tl;dr is don't use sudo in the .travis.yaml

Currently we have one usage for pointing gcc to clang for Radish

**Comment by senderista** [comment]
Heh, I had already attempted this last week but didn't get far:
```
diff --git a/.travis.yml b/.travis.yml
index ab65cf7..415b2b1 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -5,7 +5,6 @@ install:
   - pip install -r requirements-dev.txt
   - python setup.py install
   - pip install coveralls
-  - sudo ln -fs `which clang++` `which g++`
-script: nosetests --with-coverage --cover-package=raco --logging-level=WARN
+script: CXX=clang++ nosetests --with-coverage --cover-package=raco --logging-level=WARN
 after_success:
   - coveralls
```
This didn't work but I haven't dug into it further.
