### ISSUE TITLE
Radish aggregate combiner step

### ISSUE THREAD

**Issue by bmyerz** [uwescience/raco#478]
# Why
In many cases the number of unique keys seen by a given worker may be small enough to fix in local memory. Local combining before communication is a common optimization that takes advantage of these cases.

## Immediate uses
Making TPC-H Q1, Q4 faster (known constant number of keys)
Making matrix multiply queries faster (sometimes sufficiently small number of keys)

# What
Implement GroupBy as localGroupBy=>Shuffle=>localGroupBy in Radish.

# Notes
Notes from email discussion:

The general rule is DecomposeGroupBy and it actually acts on the LogicalAlgebra to turn GroupBy into GroupBy=>Shuffle=>GroupBy, so we still don't explicitly need a different parallel algebra.

The main friction point is just that Radish compiler assumes GroupBy means global groupby, while myria compiler assumes groupby means local groupby. This is where myrialang.py currently abuses the LogicalAlgebra classes by interpreting it in two different ways: before optimization it is a purely logical plan where groupby means full groupby, and after some optimization (translation) steps (fortunately encapsulated in `opt_grps_sequence`) it means partition-local groupby.

All shuffle-y operations in RadishAlgebra are hidden by global operators like RadishHashJoin and RadishGroupby. A pipelined shuffle is easy to implement in Radish (just pull out some code from those data structures that does the RPC call). Then I can introduce two kinds of operators: e.g. RadishGlobalGroupby and RadishPartitionGroupby.

Then optimization can choose either

Groupby =>    RadishPartitionGroupby(Shuffle(RadishPartitionGroupby)))
or
Groupby =>    RadishGlobalGroupby

# To do
- [x] incude myrialang.py `distributed_group_by` rule sequence in `GrappaAlgebra`
- [x] include a way to turn on/off `distributed_group_by` (should be based on cardinality but this is a TODO in DecomposeGroupBy since we don't have good statistics support anyway)
- [x] implement GrappaShuffle; should be just `Grappa::call` where lambda capture is just the input tuple
- [x] Refactor GrappaGroupBy into GrappaGlobalGroupBy
- [x] implement GrappaPartitionGroupBy
- [x] change the translation rule for GroupBy => GrappaGroupBy (must disambiguate partition/global interpretation of GroupBy)

**Comment by billhowe** [comment]
Great summary.

This is another vote for having a true logical algebra and moving shuffle
and partition  and local ops into a "parallel logical algebra."

Then, we know that group by is global group by.

Optimization then proceeds in multiple steps.  Logical->parallel->myriax.
We might have more steps as needed, depending on what patterns emerge in
the systems we want to interact with.

I think this is a nice design that is uniquely appropriate for polystores.

**Comment by bmyerz** [comment]
@billhowe Upon implementing this (in #480) I realized that we can push off an explicit refactoring of Parallel vs Logical algebra. The `DecomposeGroupby` rule that changes GroupBy to a local groupbys actually does
LogicalGroupBy =>   PhysicalGroupBy(LogicalShuffle(PhysicalGroupBy))

so the semantics of LogicalGroupBy never actually changes.
