### ISSUE TITLE
`SQLCatalog.get_sql` should support all raco aggregates

### ISSUE THREAD

**Issue by senderista** [uwescience/raco#502]
We should be able to generate SQL even for aggregates that are not explicitly supported by SQLAlchemy: "Note that any name not known to `func` generates the function name as is - there is no restriction on what SQL functions can be called, known or unknown to SQLAlchemy, built-in or user defined." (http://docs.sqlalchemy.org/en/latest/core/functions.html).

This is a prerequisite for pushing all local `GROUP BY`/`DISTINCT` aggregates into SQL:
https://github.com/uwescience/raco/issues/500
https://github.com/uwescience/raco/pull/501

**Comment by bmyerz** [comment]
@senderista I'm not entirely clear on what you are asking for. Do you just want to fill in the cases here?
https://github.com/uwescience/raco/blob/master/raco/backends/sql/catalog.py#L107

Alternatively can you provide a test case that would fail?

**Comment by senderista** [comment]
Sorry I wasn't very clear; I just want to support all the aggregates defined in `raco/raco/expression/aggregate.py` (i.e., add them as cases to the code you referenced).

**Comment by bmyerz** [comment]
#503  ready
