### ISSUE TITLE
Order ignored in partition attributes

### ISSUE THREAD

**Issue by bmyerz** [uwescience/raco#515]
Thanks to @jingjingwang and @shbae 

...

> I guess it's caused by the new RACO optimization where a shuffle is eliminated if the relation is already partitioned in the same way, but the order of the hash indices seems to be incorrect. This is the join of the JSON plan:
> 
> ```
>     "operators": [
>       {
>         "opName": "MyriaScan(shbae:graphs:toy_graph2)",
>         "opId": 18,
>         "relationKey": {
>           "relationName": "toy_graph2",
>           "userName": "shbae",
>           "programName": "graphs"
>         },
>         "opType": "TableScan"
>       },
>       {
>         "opName": "MyriaShuffleConsumer",
>         "opId": 19,
>         "argOperatorId": 20,
>         "opType": "ShuffleConsumer"
>       },
>       {
>         "argColumnNames": [
>           "row",
>           "value",
>           "value1",
>           "col",
>           "value11"
>         ],
>         "opName": "MyriaSymmetricHashJoin((($5 = $0) and ($2 = $4)); $0,$1,$3,$5,$6)",
>         "opId": 21,
>         "argChild2": "18",
>         "argChild1": "19",
>         "argSelect1": [
>           0,
>           1,
>           3
>         ],
>         "argSelect2": [
>           1,
>           2
>         ],
>         "argColumns1": [
>           0,
>           2
>         ],
>         "argColumns2": [
>           1,
>           0
>         ],
>         "opType": "SymmetricHashJoin"
>       },
> ```
> 
> operator 18 should give us tuples partitioned by ($1, $0) as specified in argColumns2, but shbae:graphs:toy_graph2 was partitioned using ($0, $1) (http://ec2-54-183-236-108.us-west-1.compute.amazonaws.com:8753/dataset/user-shbae/program-graphs/relation-toy_graph2), so there still needs to be a Shuffle. I used round-robin in my deployment so my plan had another ShuffleConsumer instead of a Scan, so I had no problem. 

I think the problem is that hash partitioning in Raco is using a set instead of a list. It is ignoring order but shouldn't be. Should be an easy fix.

**Comment by senderista** [comment]
Tracking related superfluous shuffle generation bug in https://github.com/uwescience/raco/issues/566
