### ISSUE TITLE
Implement MyriaL support for MyriaX `Split` operator

### ISSUE THREAD

**Issue by senderista** [uwescience/raco#529]
The `Split` MyriaX operator (splits string values on a regex) has been around for a while but has no support in Raco. We need to add a simple functional syntax to use it in MyriaL. (Eventually both the operator and the syntax will be superseded by a proper flatmap UDF design.)

**Comment by bmyerz** [comment]
Can you list a tiny example of what such a plan looks like? Does it assume the input is a relation of 1-arity string type?

**Comment by senderista** [comment]
This was superseded by `SplitExpression` (https://github.com/uwescience/raco/pull/537).
