### ISSUE TITLE
NetworkX regression from version 1.11 to 2.0b1 causes notebook queries to not work

### ISSUE THREAD

**Issue by orzikhd** [uwescience/raco#572]
Starting a new cluster right now and running a MyriaL query in a jupyter notebook gives the error `AttributeError: 'DiGraph' object has no attribute 'node'`. This is because in version 2.0b1 of NetworkX the attribute is `nodes`, not `node`. Queries still work in the myria-web editor though. This issue can be fixed on individual clusters by running the following and then `sudo restart myria` from the coordinator:
```
myria-cluster exec [cluster-name] --command 'sudo pip uninstall networkx -y'
```
```
myria-cluster exec [cluster-name] --command 'sudo pip install networkx'
```
Pip installs version 1.11, which is what was previously used, and works fine.

Either RACO needs to be updated to use the 2.0b1 `nodes` call or `myria-cluster create` needs to give clusters the correct version of NetworkX

**Comment by senderista** [comment]
fixed in aaa68b40, please confirm
